version: '3.9'

services:
  data_transformer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_maxSize: 1G
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/conf:/conf