version: '3.9'

services:
  data_transformer:
    build:
      context: ./data_transformer_node
      dockerfile: Dockerfile
    depends_on:
      - neo4j
      - redis

  data_collector:
    build:
      context: ./data_collector_node
      dockerfile: Dockerfile
    depends_on:
      - data_transformer
      - neo4j
      - redis

  control_node:
    build:
      context: ./control_node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - data_transformer
      - data_collector
      - neo4j
      - redis

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - control_node
      - redis

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_maxSize: 1G
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/conf:/conf

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/conf